[[0, 0, 0], 1.0, {"submitted": 1651513341.5124514, "started": 1651513341.5134516, "finished": 1651513397.6636631}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 50) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[1, 0, 0], 1.0, {"submitted": 1651513397.6916647, "started": 1651513397.6936648, "finished": 1651513436.4148796}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 50) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[2, 0, 0], 1.0, {"submitted": 1651513436.4678824, "started": 1651513436.4688828, "finished": 1651513476.5771766}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 31) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[3, 0, 0], 1.0, {"submitted": 1651513476.5871773, "started": 1651513476.5881774, "finished": 1651513515.3313932}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 20) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[4, 0, 0], 1.0, {"submitted": 1651513515.341394, "started": 1651513515.3423939, "finished": 1651513553.9526021}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 20) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[5, 0, 0], 1.0, {"submitted": 1651513553.9596026, "started": 1651513553.9606025, "finished": 1651513627.2407942}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 42) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[6, 0, 0], 1.0, {"submitted": 1651513637.4243765, "started": 1651513637.4263768, "finished": 1651513711.0625885}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 42) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[7, 0, 0], 1.0, {"submitted": 1651513711.1555936, "started": 1651513711.156594, "finished": 1651513752.825977}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 61) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[8, 0, 0], 1.0, {"submitted": 1651513752.8729796, "started": 1651513752.8739798, "finished": 1651513792.2222304}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 42) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
[[9, 0, 0], 1.0, {"submitted": 1651513792.233231, "started": 1651513792.2342312, "finished": 1651513895.9131613}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"D:/SimRL_onward/hyper_tuner.py\", line 147, in compute\n    runner.run(num_episodes=NUM_EPISODES, use_tqdm=False)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 504, in run\n    self.handle_act(parallel=n,agent1= agent_failure,agent2=agent_bal)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 540, in handle_act\n    actions_1 = agent1.act(states=self.states[parallel], parallel=parallel, independent=True)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 492, in act\n    deterministic=deterministic, **kwargs\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 620, in fn\n    fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 779, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1385, in run\n    raise six.reraise(*original_exc_info)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\six.py\", line 703, in reraise\n    raise value\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1370, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1443, in run\n    run_metadata=run_metadata)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py\", line 1201, in run\n    return self._sess.run(*args, **kwargs)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\n    run_metadata_ptr)\n  File \"C:\\Users\\reyhooni\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1167, in _run\n    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))\nValueError: Cannot feed value of shape (1, 31) for Tensor 'agent/state-input:0', which has shape '(None, 47)'\n"]
